apiVersion: apps/v1
kind: Deployment
metadata:
  name: string
spec:
  selector:
    matchLabels:
      app: string
  replicas: integer
  template:
    metadata:
      labels:
        app: string
    spec:
      imagePullSecrets: []
      containers: []
