apiVersion: v2
appVersion: "7.2.4"
description: A Helm chart for the Prometheus Fastly Exporter
name: prometheus-fastly-exporter
version: 0.1.1
keywords:
  - metrics
  - fastly
  - monitoring
home: https://github.com/fastly/fastly-exporter
maintainers:
  - name: arslanbekov
    email: arslanbekov@gmail.com
