#!/bin/bash

if [ ! -e "./VENV" ]; then
    python3 -m venv VENV    
    
    source VENV/bin/activate

    pip3 install -r requirements.txt
fi

echo " "
echo "-----INSTALLATION COMPLETE-----"
echo " "
echo "Now run 'source VENV/bin/activate'"