apiVersion: v1
kind: Service
metadata:
  name: {{ include "prom-label-proxy.fullname" . }}
  namespace: {{ template "prom-label-proxy.namespace" . }}
  labels:
    {{- include "prom-label-proxy.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "prom-label-proxy.selectorLabels" . | nindent 4 }}
