{{- if .Values.serviceMonitor.enabled }}
{{- range .Values.serviceMonitor.params }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "prometheus-snmp-exporter.fullname" $  }}-{{ .name }}
  {{- if $.Values.serviceMonitor.namespace }}
  namespace: {{ $.Values.serviceMonitor.namespace }}
  {{- end }}
  labels:
    {{- include "prometheus-snmp-exporter.labels" $ | indent 4 }}
    {{- range $key, $value := .labels | default $.Values.serviceMonitor.selector }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  endpoints:
  - port: http
    honorLabels: {{ $.Values.serviceMonitor.honorLabels }}
    path: {{ $.Values.serviceMonitor.path }}
    {{- if or .interval $.Values.serviceMonitor.interval }}
    interval: {{ .interval | default $.Values.serviceMonitor.interval }}
    {{- end }}
    scrapeTimeout: {{ .scrapeTimeout | default $.Values.serviceMonitor.scrapeTimeout }}
    params:
      module: {{ .module | default $.Values.serviceMonitor.module }}
      target:
      - {{ .target }}
    metricRelabelings:
      - sourceLabels: [instance]
        targetLabel: instance
        replacement: {{ .target }}
      - sourceLabels: [target]
        targetLabel: target
        replacement: {{ .name }}
        {{- range $targetLabel, $replacement := .additionalMetricsRelabels | default $.Values.serviceMonitor.additionalMetricsRelabels }}
      - targetLabel: {{ $targetLabel }}
        replacement: {{ $replacement }}
        {{- end }}
    {{- if or .relabelings }}
    relabelings: {{ toYaml .relabelings | default $.Values.serviceMonitor.relabelings | nindent 8 }}
    {{- end }}
  jobLabel: "{{ $.Release.Name }}"
  selector:
    matchLabels:
      {{- include "prometheus-snmp-exporter.selectorLabels" $ | indent 6 }}
{{- end }}
{{- end -}}
