apiVersion: v1
appVersion: 0.10.1
description: A Helm chart for prometheus-nats-exporter
name: prometheus-nats-exporter
version: 2.10.1
home: https://github.com/nats-io/prometheus-nats-exporter
sources:
  - https://github.com/nats-io/prometheus-nats-exporter
keywords:
  - nats
  - prometheus
  - exporter
maintainers:
  - email: okgolove@markeloff.net
    name: okgolove
  - email: carlos@carlosbecker.com
    name: caarlos0
